In [1]:
import numpy as np
import matplotlib.pyplot as plt
# coo escribir unvector con numpy
x=np.array([1,2.5,3,4,5])

print("x=",x)

x= [1.  2.5 3.  4.  5. ]


In [2]:
# COMO ESCRIBIR UNA MATRIZ
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("A=",A)

A= [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# SUMA DE MATRICES
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,1,1],[2,2,2],[3,3,3]])

C=A+B
print("C=",C)

In [ ]:
# multiplicaicon por escarlar

A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=2*A
print("B=",B)

In [3]:
# multiplicacion de vectores

x=np.array([1,2,3])
y=np.array([4,5,6])

z=np.dot(x,y)

print("z=",z)

# multiplicacion de matrices    

A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,1,1],[2,2,2],[3,3,3]])

C=np.dot(A,B)
print("C=",C)

#otra forma 

C=A.dot(B)
print("C=",C)
# otra forma de multiplicar matrices

C=A@B

print("C=",C)

z= 32
C= [[14 14 14]
 [32 32 32]
 [50 50 50]]
C= [[14 14 14]
 [32 32 32]
 [50 50 50]]
C= [[14 14 14]
 [32 32 32]
 [50 50 50]]


In [5]:
# trnaspuesta de una matriz

A=np.array([[1,2,3],[4,5,6],[7,8,9]])

B=A.T
print("B=",B)

# otra forma
B=A.transpose()

print("B=",B)

B= [[1 4 7]
 [2 5 8]
 [3 6 9]]
B= [[1 4 7]
 [2 5 8]
 [3 6 9]]
