In [2]:
import numpy as np

A=np.array([[1,2],[4,5]])

print(A)

[[1 2]
 [4 5]]


In [8]:
x=np.array([[1],[2]])
x1=x/np.linalg.norm(x)
x1

array([[0.4472136 ],
       [0.89442719]])

In [14]:
x2=A@x
x2=x2/np.linalg.norm(x2)
x3=A@x2
x3

array([[2.21982022],
       [6.05405515]])

In [16]:
x3=x3/np.linalg.norm(x3)
x4=A@x3
x4

array([[2.22200728],
       [6.07140018]])

In [15]:
x4=x4/np.linalg.norm(x4)
x5=A@x4
x5

array([[2.22185516],
       [6.07016638]])

In [18]:
[a,v]=np.linalg.eig(A)
a

array([-0.46410162,  6.46410162])

In [19]:
v

array([[-0.80689822, -0.34372377],
       [ 0.59069049, -0.9390708 ]])